package com.minexd.zoot.profile.punishment.command;

import com.minexd.zoot.Zoot;
import com.minexd.zoot.network.packet.PacketSuccessfulAuth;
import com.minexd.zoot.profile.Profile;
import com.minexd.zoot.profile.punishment.AuthCode;
import com.minexd.zoot.util.CC;
import net.frozenorb.qlib.command.Command;
import net.frozenorb.qlib.command.Param;
import org.bukkit.entity.Player;

public class LoginCommand {

    @Command(names = "login", permission = "zoot.twofa", description = "Use a 2FA code generated by a discord bot to authenticate")
    public static void twofaCommand(Player player, @Param(name = "password") String password) {
        Profile profile = Profile.getByUuid(player.getUniqueId());
        if (profile.getDiscordID() == null) {
            player.sendMessage(CC.translate("&cPlease go into the staff discord, and DM the 2FA bot with the message 'authme'"));
        }
        AuthCode code = null;
        for (AuthCode codeLoop : Profile.getAuthCodes()) {
            System.out.println(codeLoop.getAuthKey() + "\n" + password);
            System.out.println(codeLoop.getDiscordID() + "\n" + profile.getDiscordID());
            if (codeLoop.getAuthKey().equalsIgnoreCase(password))

                if (codeLoop.getDiscordID().equalsIgnoreCase(profile.getDiscordID()) || profile.getDiscordID() == null)
                    //if (System.currentTimeMillis() - codeLoop.getAuthCreatedAt() < 30*60000) //30minutes
                    code = codeLoop;
        }

        if (code != null) {
            profile.getOptions().setTwoFA(false);
            player.sendMessage(CC.translate("&aYou have authenticated."));
            if (profile.getDiscordID() == null)
                profile.setDiscordID(code.getDiscordID());
            Profile.getAuthCodes().remove(code);
            profile.setLastAuthenticated(System.currentTimeMillis());
            profile.getAuthedips().add(profile.getCurrentAddress());
            profile.save();
            Zoot.get().getPidgin().sendPacket(new PacketSuccessfulAuth(player.getUniqueId(), code.getDiscordID()));
        } else {
            player.sendMessage(CC.translate("&cEither your code is invalid, or your discord profile doesn't match."));
        }

    }
}
